modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
license = "${mod_license}"
issueTrackerURL="https://github.com/GreenhouseTeam/greenhouse-config/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}+${minecraft_version}"
displayName = "${mod_name}"
displayURL="https://github.com/GreenhouseTeam/greenhouse-config"
logoFile="${mod_id}.png"
logoBlur=false
credits="${mod_contributors}"
authors = "${mod_author}"
description = '''${mod_description}'''

[[accessTransformers]]
file="greenhouseconfig.cfg"

[[dependencies.${mod_id}]]
modId = "neoforge"
type="required"
versionRange = "${neoforge_loader_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type="required"
versionRange = "${neoforge_minecraft_version_range}"
ordering = "NONE"
side = "BOTH"